name: Regression Suite
on: [push]

jobs:
  regression_tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pytest coverage
          pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Execute Test
        run: coverage report --include=src* --fail-under=80

  mypy:
    name: Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
          
      - name: Install Requirements
        run:  pip install mypy

      - name: Execute Test
        run: mypy src
